# Taken from the cucumber-rails project.
# IMPORTANT: This file is generated by cucumber-sinatra - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-sinatra. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))

module WithinHelpers
  def with_scope(locator)
    locator ? within(locator) { yield } : yield
  end
end
World(WithinHelpers)

Given(/^I am on the homepage$/) do
  visit "/"
end

Then(/^I should see "(.*?)"$/) do |arg1|
  expect(page).to have_content arg1
end

When(/^I click "(.*?)"$/) do |arg1|
  click_link "Rock"
end

When(/^I fill in Gus and click submit$/) do
  fill_in "name", :with => "Gus"
  click_button "submit"
end

Given(/^I have registered my name$/) do
  visit "/"
  fill_in "name", :with => "Gus"
  click_button "submit"
end

When(/^I follow "(.*?)"$/) do |arg1|
  click_link "Play Game"
end

Given(/^I am on the choice page$/) do
  visit "/choice"
end











